-- Eliminar esquemas (CASCADE elimina todo el contenido dentro)
DROP SCHEMA IF EXISTS security CASCADE;
DROP SCHEMA IF EXISTS clientes CASCADE;
DROP SCHEMA IF EXISTS catalogo CASCADE;
DROP SCHEMA IF EXISTS promociones CASCADE;
DROP SCHEMA IF EXISTS ventas CASCADE;
DROP SCHEMA IF EXISTS logistica CASCADE;
DROP SCHEMA IF EXISTS inventario CASCADE;