services:
  security-service:
    build: .
    container_name: accesorios-dm-security-prod
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - PORT=8888
      - HOST=0.0.0.0
    volumes:
      - ./app:/app/app
    networks:
      - accesorios-dm-net-prod

networks:
  accesorios-dm-net-prod:
    external: true
    name: accesorios-dm-database_accesorios-network-prod